# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  pushToGitLab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Configure Git
#         run: |
#           git config --global user.name "Kinjal Raykarmakar"
#           git config --global user.email "kinjalrk2k@gmail.com"
      - name: Push to GitLab
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'Kinjal Raykarmakar'
          email: 'kinjalrk2k@gmail.com'
          actor: 'Kinjalrk2k'
          token: '${{ secrets.GL_TOKEN }}'
      - run: |
          git remote add gitlab git@gitlab.com:Kinjalrk2k/ureckon-backend-test.git
          yarn run deploy gitlab/main
